services:
  database:
    image: 'postgres:17.0'
    ports:
      - "5432:5432"
    volumes:
      - "./db:/var/lib/postgresql/data/"
    env_file:
      - .env
    environment:
      POSTGRES_DB: GRAAL_CAR